{
 "title": "Kafka",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "ClickHouse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CH: Rows insertion rate",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_InsertedRows[5m])"
    }
   ]
  },
  {
   "title": "CH: Number of merged rows per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_MergedRows[5m])"
    }
   ]
  },
  {
   "title": "CH: Merges rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_Merge[1m])"
    }
   ]
  },
  {
   "title": "CH: SELECT query rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_SelectQuery[1m])"
    }
   ]
  },
  {
   "title": "CH: Queue size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_ReplicasSumQueueSize"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Messages In per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total[5m])"
    }
   ]
  },
  {
   "title": "Kafka: Requests per second",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_requests_total[5m])"
    }
   ]
  },
  {
   "title": "Broker state",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_kafkaserver_brokerstate"
    }
   ]
  },
  {
   "title": "Total number of messages received",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total"
    }
   ]
  },
  {
   "title": "JVM mb used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Bytes In Per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " rate(kafka_server_brokertopicmetrics_bytesin_total[5m])"
    }
   ]
  },
  {
   "title": "Kafka CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])"
    }
   ]
  },
  {
   "title": "Bytest Out per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesout_total[5m])"
    }
   ]
  },
  {
   "title": "Kafka: Network: queue size",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestchannel_requestqueuesize",
     "legendFormat": "Request queue size"
    },
    {
     "expr": "kafka_network_requestchannel_responsequeuesize",
     "legendFormat": "Response queue size"
    }
   ]
  },
  {
   "title": "Request: Average time per second to send a response to a request",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_responsesendtimems[5m])"
    }
   ]
  },
  {
   "title": "Disk IO per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_kafkaserver_linux_disk_write_bytes[5m])",
     "legendFormat": "Disk write bytes"
    },
    {
     "expr": "rate(kafka_server_kafkaserver_linux_disk_read_bytes[5m])",
     "legendFormat": "Disk read bytes"
    }
   ]
  },
  {
   "title": "Failed produce() requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_failedproducerequests_total"
    }
   ]
  }
 ]
}