{
 "title": "Kafka",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Broker state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_kafkaserver_brokerstate"
    }
   ]
  },
  {
   "title": "Total number of messages received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total"
    }
   ]
  },
  {
   "title": "Messages In per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total[5m])"
    }
   ]
  },
  {
   "title": "Bytest Out per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesout_total[5m])"
    }
   ]
  },
  {
   "title": "Failed produce() requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_failedproducerequests_total"
    }
   ]
  },
  {
   "title": "Bytes In Per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " rate(kafka_server_brokertopicmetrics_bytesin_total[5m])"
    }
   ]
  }
 ]
}